name: Push on master

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            vendor/
            web/
            node_modules/
          key: build-${{ hashFiles('composer.lock', 'package-lock.json') }}

      - name: Setup environment
        run: |
          docker-compose up -d web
          sleep 5

      - name: Setup package, test package
        run: |
          docker-compose exec -T web composer install
          docker-compose exec -T web ./vendor/bin/grumphp run

      - name: Test Drupal Template
        run: |
          docker-compose exec -T web composer setup-drupal
          docker-compose exec -w ${PWD}/builds/drupal -T web ./vendor/bin/phpcs || echo "Proceed"
          docker-compose exec -w ${PWD}/builds/drupal -T web ./vendor/bin/phpstan || echo "Proceed"
          docker-compose exec -w ${PWD}/builds/drupal -T web ./vendor/bin/grumphp run || echo "Proceed"