name: Push on master

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          docker-compose up -d web
          sleep 5

      - name: Setup package, test package
        run: |
          docker-compose exec -T web composer install
          docker-compose exec -T web ./vendor/bin/grumphp run

      - name: Test Drupal Template
        run: |
          docker-compose exec -T web composer setup-drupal
          docker-compose exec -w ${PWD}/../builds/drupal -T web composer phpcs || echo "Proceed"
          docker-compose exec -w ${PWD}/../builds/drupal -T web composer phpstan || echo "Proceed"
          docker-compose exec -w ${PWD}/../builds/drupal -T web ./vendor/bin/grumphp run || echo "Proceed"